export const demoOverallSumValueData = [
  {
    status: "In progress",
    category: "Man",
    sqcd: "Safety",
    value: 10,
  },
  {
    status: "In progress",
    category: "Man",
    sqcd: "Quality",
    value: 28,
  },
  {
    status: "In progress",
    category: "Man",
    sqcd: "Cost",
    value: 26,
  },
  {
    status: "In progress",
    category: "Man",
    sqcd: "Delivery",
    value: 14,
  },
  {
    status: "In progress",
    category: "Machine",
    sqcd: "Safety",
    value: 19,
  },
  {
    status: "In progress",
    category: "Machine",
    sqcd: "Quality",
    value: 29,
  },
  {
    status: "In progress",
    category: "Machine",
    sqcd: "Cost",
    value: 22,
  },
  {
    status: "In progress",
    category: "Machine",
    sqcd: "Delivery",
    value: 15,
  },
  {
    status: "In progress",
    category: "Method",
    sqcd: "Safety",
    value: 13,
  },
  {
    status: "In progress",
    category: "Method",
    sqcd: "Quality",
    value: 16,
  },
  {
    status: "In progress",
    category: "Method",
    sqcd: "Cost",
    value: 22,
  },
  {
    status: "In progress",
    category: "Method",
    sqcd: "Delivery",
    value: 22,
  },
  {
    status: "In progress",
    category: "Material",
    sqcd: "Safety",
    value: 28,
  },
  {
    status: "In progress",
    category: "Material",
    sqcd: "Quality",
    value: 25,
  },
  {
    status: "In progress",
    category: "Material",
    sqcd: "Cost",
    value: 25,
  },
  {
    status: "In progress",
    category: "Material",
    sqcd: "Delivery",
    value: 18,
  },
  {
    status: "In progress",
    category: "Measurement",
    sqcd: "Safety",
    value: 2,
  },
  {
    status: "In progress",
    category: "Measurement",
    sqcd: "Quality",
    value: 7,
  },
  {
    status: "In progress",
    category: "Measurement",
    sqcd: "Cost",
    value: 29,
  },
  {
    status: "In progress",
    category: "Measurement",
    sqcd: "Delivery",
    value: 12,
  },
  {
    status: "In progress",
    category: "Environment",
    sqcd: "Safety",
    value: 5,
  },
  {
    status: "In progress",
    category: "Environment",
    sqcd: "Quality",
    value: 11,
  },
  {
    status: "In progress",
    category: "Environment",
    sqcd: "Cost",
    value: 7,
  },
  {
    status: "In progress",
    category: "Environment",
    sqcd: "Delivery",
    value: 12,
  },
  {
    status: "Done",
    category: "Man",
    sqcd: "Safety",
    value: 6,
  },
  {
    status: "Done",
    category: "Man",
    sqcd: "Quality",
    value: 17,
  },
  {
    status: "Done",
    category: "Man",
    sqcd: "Cost",
    value: 15,
  },
  {
    status: "Done",
    category: "Man",
    sqcd: "Delivery",
    value: 11,
  },
  {
    status: "Done",
    category: "Machine",
    sqcd: "Safety",
    value: 18,
  },
  {
    status: "Done",
    category: "Machine",
    sqcd: "Quality",
    value: 26,
  },
  {
    status: "Done",
    category: "Machine",
    sqcd: "Cost",
    value: 27,
  },
  {
    status: "Done",
    category: "Machine",
    sqcd: "Delivery",
    value: 14,
  },
  {
    status: "Done",
    category: "Method",
    sqcd: "Safety",
    value: 29,
  },
  {
    status: "Done",
    category: "Method",
    sqcd: "Quality",
    value: 10,
  },
  {
    status: "Done",
    category: "Method",
    sqcd: "Cost",
    value: 18,
  },
  {
    status: "Done",
    category: "Method",
    sqcd: "Delivery",
    value: 6,
  },
  {
    status: "Done",
    category: "Material",
    sqcd: "Safety",
    value: 23,
  },
  {
    status: "Done",
    category: "Material",
    sqcd: "Quality",
    value: 22,
  },
  {
    status: "Done",
    category: "Material",
    sqcd: "Cost",
    value: 26,
  },
  {
    status: "Done",
    category: "Material",
    sqcd: "Delivery",
    value: 28,
  },
  {
    status: "Done",
    category: "Measurement",
    sqcd: "Safety",
    value: 8,
  },
  {
    status: "Done",
    category: "Measurement",
    sqcd: "Quality",
    value: 11,
  },
  {
    status: "Done",
    category: "Measurement",
    sqcd: "Cost",
    value: 23,
  },
  {
    status: "Done",
    category: "Measurement",
    sqcd: "Delivery",
    value: 18,
  },
  {
    status: "Done",
    category: "Environment",
    sqcd: "Safety",
    value: 15,
  },
  {
    status: "Done",
    category: "Environment",
    sqcd: "Quality",
    value: 19,
  },
  {
    status: "Done",
    category: "Environment",
    sqcd: "Cost",
    value: 9,
  },
  {
    status: "Done",
    category: "Environment",
    sqcd: "Delivery",
    value: 30,
  },
];

export const demoOverallSumPercentData = [
  { status: "Done", category: "Man", percent: 10 },
  { status: "Done", category: "Machine", percent: 30 },
  { status: "Done", category: "Method", percent: 31 },
  { status: "Done", category: "Material", percent: 10 },
  { status: "Done", category: "Measurement", percent: 5 },
  { status: "Done", category: "Environment", percent: 5 },
  { status: "In progress", category: "Man", percent: 4 },
  { status: "In progress", category: "Machine", percent: 3 },
  { status: "In progress", category: "Method", percent: 0 },
  { status: "In progress", category: "Material", percent: 0 },
  { status: "In progress", category: "Measurement", percent: 1 },
  { status: "In progress", category: "Environment", percent: 1 },
];

export const demoHistoryLineData = [
  { date: "01-09-2022", line: "Line 1", value: 3 },
  { date: "02-09-2022", line: "Line 1", value: 5 },
  { date: "03-09-2022", line: "Line 1", value: 1 },
  { date: "04-09-2022", line: "Line 1", value: 3 },
  { date: "05-09-2022", line: "Line 1", value: 0 },
  { date: "01-09-2022", line: "Line 2", value: 6 },
  { date: "02-09-2022", line: "Line 2", value: 3 },
  { date: "03-09-2022", line: "Line 2", value: 7 },
  { date: "04-09-2022", line: "Line 2", value: 0 },
  { date: "05-09-2022", line: "Line 2", value: 3 },
  { date: "01-09-2022", line: "Line 3", value: 1 },
  { date: "02-09-2022", line: "Line 3", value: 2 },
  { date: "03-09-2022", line: "Line 3", value: 6 },
  { date: "04-09-2022", line: "Line 3", value: 3 },
  { date: "05-09-2022", line: "Line 3", value: 6 },
];

export const demoHistoryTotalByLineData = [
  {line:"Line 1",Total: 10,"In progress": 2,Done: 8},
  {line:"Line 2",Total: 18,"In progress": 6,Done: 12},
  {line:"Line 3",Total: 13,"In progress": 3,Done: 10},
  {line:"Line 4",Total: 4,"In progress": 1,Done: 3},
  {line:"Line 5",Total: 8,"In progress": 3,Done: 5},
  {line:"Line 6",Total: 2,"In progress": 0,Done: 2},
  {line:"Line 7",Total: 9,"In progress": 4,Done: 5},
  {line:"Line 8",Total: 7,"In progress": 3,Done: 4},
  {line:"Line 9",Total: 6,"In progress": 1,Done: 5},
  {line:"Line 11",Total: 4,"In progress": 0,Done: 4},
  {line:"Line 12",Total: 3,"In progress": 1,Done: 2},
  {line:"Line 13",Total: 8,"In progress": 2,Done: 6}
]